### ISSUE TITLE
Page Freezes When You Expand to Desktop from Mobile (env-prototype)

### ISSUE THREAD

**Issue by sdurphy** [baltimorecounty/restaurant-week#40]
The page freezes when you expand to desktop from mobile, if you leave the menu open on mobile.

**Expected:** The mobile menu dissapears if you expand from mobile to desktop size.
**Actual:** The menu disappears, however the disable-scroll class written on the html tag by the js string remains. This causes the page to remain in a position: fixed;.
**Steps to recreate:** Open the RW Page > Reduce the width on desktop until you can toggle the mobile menu > Click the menu > Expand window to desktop size.

**Comment by martypowell** [comment]
fixed in dev.
