### ISSUE TITLE
Request - Categories

### ISSUE THREAD

**Issue by theilman7** [baltimorecounty/restaurant-week#63]
Wanted to see if it was possible to limit the number of categories that can be added to a particular restaurant listing to 3. Trying to avoid a gratuitous amount of categories, added to one listing.

**Comment by martypowell** [comment]
@theilman7 @sdurphy it doesn't appear that there is a way in Site Executive to limit the number of options a user can select. Unless we had just 1, which is possible but I don't think we want that.

This would need to be something communicated to the customer, and they would have to follow it.
