### ISSUE TITLE
Issue When Expanding a Window With the Mobile Menu Open

### ISSUE THREAD

**Issue by theilman7** [baltimorecounty/restaurant-week#72]
Expected: When viewing the page and mobile menu at a smaller scale, the user can expand the window and browse the page as usual while the menu disappears.

Actual: When viewing the page at a smaller scale, and the mobile menu is open, if the user expands the window back to desktop size, scrolling is locked and the header height is significantly larger.

Steps to reproduce (Can be reproduced in Chrome, IE and Firefox):
1. Reduce the window to mobile view size, so that the mobile menu hamburger icon appears.
2. Open the mobile menu.
3. With the mobile menu still open, expand the window width.
4. When the menu disappears and the frame returns to desktop size, observe the header sizing and attempt to scroll down the page.

**Comment by martypowell** [comment]
@theilman7 confirmed, working on this.

**Comment by martypowell** [comment]
@theilman7 in dev, please confirm and close if you are happy

**Comment by theilman7** [comment]
Noticed the issue is occurring on sub pages. May need to mirror the fix on those as well.
_TH

**Comment by martypowell** [comment]
per @sdurphy this was fixed by removing the Facebook resizing script. the changes are in dev and stage, please close if you guys are happy with this.

fyi @theilman7

**Comment by sdurphy** [comment]
Thanks @martypowell
