### ISSUE TITLE
Adding mockup and hex codes for mobile menu recolor

### ISSUE THREAD

**Issue by theilman7** [baltimorecounty/restaurant-week#73]
Buttons and Hamburger Icon Background: #9a1b27
Background: #420a0f

![mockup-menu-dark](https://user-images.githubusercontent.com/34519645/42183911-8bd7030c-7e11-11e8-99e9-e3fa4a95af53.png)

**Comment by martypowell** [comment]
@theilman7 this is in dev, can you please confirm and then close this issue?

**Comment by sdurphy** [comment]
Confirmed that this is in dev. Closing.
