### ISSUE TITLE
Safari on Mac Bug

### ISSUE THREAD

**Issue by theilman7** [baltimorecounty/restaurant-week#74]
Please note, the version of Safari tested in is: 9.1.2.

Expected: When opening the mobile menu in Safari, the menu options will display.

Actual: The mobile menu opens, however the links aren't visible (with the exception of the Facebook Icon).

Steps to reproduce: 
1. Open http://dev.baltimorecountyrestaurantweek.com/index.html in Safari.
2. Reduce window to mobile dimensions so that the menu appears.
3. Click the hamburger icon to open the menu.
![screen shot 2018-07-03 at 9 14 12 am](https://user-images.githubusercontent.com/34519645/42221980-ed3cf2e2-7ea1-11e8-9a08-688600877f3e.png)

**Comment by martypowell** [comment]
@theilman7 please close if you are happy

**Comment by theilman7** [comment]
This appears to be resolved. Closing ticket.

Thank you!
